tenable/nessrest

nessrest/ness6rest.py
This uses a new API call to enforce plugin constraints and gather info for reporting.
=> pulling additional plugin info

nessrest/ness6rest.py
I want to be able to run a scan with a policy that is already created through the web-interface. I could not find a way to do this.
=> Add policy_set() for selecting an existing policy.

nessrest/ness6rest.py
It would be nice to be able to set a scan name that is not the same as the policy name.
=> scan_add(): Make it possible to set scan name.

nessrest/nessus-scan
Example implementation for scanning a specific target with an already
existing policy.
=> Add nessus-scan script.

nessrest/credentials.py
=> Added credentials for database, cloud, misc

nessrest/ness6rest.py
Added reset of self.req to empty dict if no text returned.
=> Json exception when no text

nessrest/ness6scan.py
This is more for review and conversation.  Goal of this class is:
* Object has little to no output, other than some errors
* Built to work with Scans and not require Policies
* Builds the in memory object to limit scan configure/create.
It uses much of the underpinnings of ness6rest.py
This was worked on to as the configure on call was causing some issues with what I was doing, and required a policy build before scan.
=> Scan specific object

nessrest/ness6rest.py
Some functions I have had in my tree for a while, maby you will find them useful as well.
=> Report management

scripts/nessus_download_all.py
I've created a directory where I'll build some scripts that I earlier used with another nessus python lib that doesn't work anymore. The scripts aren't finished products but should allow non python devvers to make it work with minor changes.
First script is a script to download all available scans as .nessus (xml) files.
(new to git / github, if I should send a pull request against another branch let me know)
=> download script, downloading all scans as .nessus

nessrest/ness6rest.py
Dead code from the time before we had multiple scanners.
=> Removed a duplicate setting

scripts/nessus_nmapxml.py
Added nessus nmap output script with comments / url's in head.
Nasl is to be downloaded seperately just as people have to make a policy themselves that can actually use a nasl.
=> added nessus_nmapxml.py, can run nessus based on nmap xml output

nessrest/ness6rest.py
Modified the download_scan function to include the option to export the scan results in 'Nessus DB' format with a password of 'test'.  In order to get the DB to save correctly, I also modified the action function to return req.content instead of req.text when 'if download' is true.
=> Added ability to download scan results in Nessus DB format

nessrest/ness6rest.py, nessrest/ness_rest
Tested and confirmed in the UI
=> Code to reduce checks and increase timeout.

scripts/nessus_download_all.py
Adds support for the encrypted nessus db format to the download all script.
=> Allow db exporting in download all

nessrest/ness6rest.py
Added the capability to download as HTML. Needed to include specific chapters such as: vuln_hosts_summary, vuln_by_host, compliance_exec, remediations, vuln_by_plugin, compliance
```
modified:   nessrest/ness6rest.py
```
=> download HTML chapers

README.md, nessrest/ness6rest.py
Added an optional scan start time to scan_add() and added its corresponding documentation. Tested on Nessus 6.10.5
=> Added an optional scan start time to scan_add()

nessrest/ness6rest.py
Added policy_delete function. 
This is useful to create temp policies (copy a policy, edit it, scan and delete it).
=> Added policy_delete function

nessrest/ness6rest.py
Hi maintainer,
I've added functionality to be able to retrieve a list of scans based on a folder within Nessus.
Best regards,
Frank
=> new method: fetch list of scans from a folder

nessrest/credentials.py, nessrest/ness6rest.py, nessrest/ness6scan.py
Dear Maintainer,
I've created some new functionality including these changes, as this is not new functionality I will create separate pull requests for the new functionality.
Best regards,
Frank
=> Small code corrections

README.md, nessrest/ness6rest.py
I've created a function to delete scans. This is needed because a policy only can be deleted when it's not being used by scans.
=> Remove scan
